field: 635bb1d5-cf1d-4684-959b-c5ab4909d302 # Post Content
fieldLayouts:
  e3d102d4-423d-4363-a16d-8faf0fef06e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b78c2c45-0e70-410d-988f-d5e56b5dc276 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57363217-5f09-4a68-b843-dfbe1321c608
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0f92f9b-ad9d-44e8-9ea2-c4c1b60a33b4
        userCondition: null
fields:
  b78c2c45-0e70-410d-988f-d5e56b5dc276: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a9f2c73d-f1e7-4e78-a6fd-9f1a0b0c54a2' # Blog
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a9f2c73d-f1e7-4e78-a6fd-9f1a0b0c54a2' # Blog
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
