fieldLayouts:
  6500fdac-eccd-46d5-adcc-1d007e250fe4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab46802f-c527-4d80-8c21-1de9f90bcfb6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c698b2c2-c623-4bb6-b6fe-fce7eb6d91e3
        userCondition: null
handle: about
hasTitleField: false
name: About
section: c08fcfac-1856-468b-83fe-575494066cd1 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
