columnSuffix: null
contentColumnType: string
fieldGroup: 8bd94919-75dc-485a-b23d-e4877dc1f7bc # Blog Post Fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
