fieldLayouts:
  8326c837-c7b0-4d3a-82cc-68ebbb7d1147:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 116045fb-c6ff-4f45-a7d0-8039c2fd245d # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df283c8b-58f6-4b19-a92b-b87246487963
            userCondition: null
            warning: null
            width: 100
        name: 'Site Information'
        uid: 7c80cbf9-1d2d-42d5-8ccd-1f75b4e8ee18
        userCondition: null
handle: siteInformation
name: 'Site Information'
sortOrder: 1
